kind: pipeline
name: default

steps:
# Create Docker image and push to HDAP Docker registry
- name: deploy_application_image
  image: plugins/docker
  settings:
    repo: gt-build.hdap.gatech.edu/emergency-department-triage-system
    context: app
    dockerfile: app/Dockerfile
    tags:
      - latest

volumes:
- name: dockersock
  temp: {}
trigger:
  branch:
  - deploy
  event:
  - push
