# The namespace to deploy your application
global:
  namespace: ns-emergency-department-triage-system

# Default values for webapp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
# REMOVE THIS SECTION IF YOUR APPLICATION DOES NOT HAVE A FRONT END
frontend:
  #name is a DNS-1035 label and must consist of lower case alphanumeric characters or '-', start with an alphabetic character, and end with an alphanumeric character (e.g. 'my-name',  or 'abc-123')
  name: edtsfrontend
  port: 80
  replicaCount: 1
  proxy:
    incomingPath: /edtsfrontend/
    containerPath: "" # The empty string "" means use same as incomingPath, otherwise the value in the string will replace the value of incomingPath when traffic is sent to the application in the deployed container
  image:
    repository: gt-build.hdap.gatech.edu/Emergency-Department-Triage-System
    tag: latest
    pullPolicy: Always
