# The namespace to deploy your application
global:
  namespace: ns-emergency-department-triage-system

frontend:
  name: edtsfrontend
  port: 80
  replicaCount: 1
  proxy:
    incomingPath: /edtsfrontend/
    containerPath: "" # The empty string "" means use same as incomingPath, otherwise the value in the string will replace the value of incomingPath when traffic is sent to the application in the deployed container
  image:
    repository: gt-build.hdap.gatech.edu/Emergency-Department-Triage-System
    tag: latest
    pullPolicy: Always
